<a href="https://colab.research.google.com/github/tommystarrrrrrr/2025_Kecerdasan-Buatan/blob/main/Jobsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Operasi matematika menggunakan python

## a.	Mendapatkan nilai minimum dan maksimum

In [9]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print("Nilai minimum:", x)
print("Nilai maksimum:", y)

Nilai minimum: 5
Nilai maksimum: 18


## b.	Mendapatkan nilai absolut

In [10]:
x = abs(-7.25)
print("Nilai absolut:", x)

Nilai absolut: 7.25


## c.	Mendapatkan nilai pangkat

In [11]:
import math
x = math.pow(4, 3)

print("Hasil 4 pangkat 3:", x)

Hasil 4 pangkat 3: 64.0


## d.	Mendapatkan nilai akar

In [12]:
import math
x = math.sqrt(64)

print("Akar kuadrat dari 64:", x)

Akar kuadrat dari 64: 8.0


## e.	Mendapatkan nilai pembulatan

In [13]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

print("Pembulatan ke atas (ceil):", x)
print("Pembulatan ke bawah (floor):", y)

Pembulatan ke atas (ceil): 2
Pembulatan ke bawah (floor): 1


## f.	Mendapatkan nilai konstanta (PI)

In [14]:
import math
x = math.pi

print("Nilai π (pi):", x)

Nilai π (pi): 3.141592653589793


# 3.	Menggunakan Fungsi MATH

### Beberapa fungsi MATH yang tersedia dan dapat di panggil adalah sebagai berikut:

In [21]:
import math  # Mengimpor modul math

# Menggunakan berbagai fungsi dari math
angka = 45

print("Nilai sinus dari 45 derajat:", math.sin(math.radians(angka)))
print("Nilai cosinus dari 45 derajat:", math.cos(math.radians(angka)))
print("Nilai tangen dari 45 derajat:", math.tan(math.radians(angka)))

print("Logaritma natural dari 10:", math.log(10))
print("Logaritma basis 10 dari 1000:", math.log10(1000))

print("45 radian dalam derajat:", math.degrees(math.pi / 4))

# Menghitung jarak antara dua titik (3,4) dan (0,0)
p1 = (3, 4)
p2 = (0, 0)
print("Jarak Euclidean antara (3,4) dan (0,0):", math.dist(p1, p2))

# Faktorial dari 5
print("Faktorial dari 5:", math.factorial(5))

# Sisa pembagian dari 17 dibagi 4
print("Sisa pembagian 17 ÷ 4:", math.fmod(17, 4))

# Mengecek apakah angka NaN (Not a Number)
nan_val = float('nan')
print("Apakah NaN?", math.isnan(nan_val))

# Fungsi gamma dari 5 (faktorial umum)
print("Nilai gamma dari 5:", math.gamma(5))

# Permutasi dari 5 elemen yang diambil 2
print("Permutasi 5P2:", math.perm(5, 2))

Nilai sinus dari 45 derajat: 0.7071067811865475
Nilai cosinus dari 45 derajat: 0.7071067811865476
Nilai tangen dari 45 derajat: 0.9999999999999999
Logaritma natural dari 10: 2.302585092994046
Logaritma basis 10 dari 1000: 3.0
45 radian dalam derajat: 45.0
Jarak Euclidean antara (3,4) dan (0,0): 5.0
Faktorial dari 5: 120
Sisa pembagian 17 ÷ 4: 1.0
Apakah NaN? True
Nilai gamma dari 5: 24.0
Permutasi 5P2: 20


# 4.	Operasi matriks dan vektor dengan python

## a.	Membuat matriks di pyhon

In [16]:
import numpy as np

A = np.array([[80, 30, 25],
              [50, 20, 10]])

B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B

print("Matriks A:\n", A)
print("Matriks B:\n", B)
print("Hasil penjumlahan A + B:\n", hasil)

Matriks A:
 [[80 30 25]
 [50 20 10]]
Matriks B:
 [[30 60 15]
 [10 30 30]]
Hasil penjumlahan A + B:
 [[110  90  40]
 [ 60  50  40]]


## b.	Melakukan operasi dot product

In [17]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil dot product A . B:", hasil)

Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil dot product A . B: 2025


## c.	Melakukan operasi cross product

In [18]:
import numpy as np

A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.cross(A, B)

print("Vektor A:", A)
print("Vektor B:", B)
print("Hasil cross product A × B:", hasil)

Vektor A: [10 20 15]
Vektor B: [16 67 35]
Hasil cross product A × B: [-305 -110  350]


# E.	TUGAS PRAKTIKUM

## 1 a.

In [22]:
import numpy as np

A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])

hasil_AxB = np.dot(A, B)
print(hasil_AxB)

[[7 2]
 [4 2]]


## 1 b.

In [23]:
C = np.array([[-1, 1, 2], [2, 0, -1]])

hasil_BxC = np.dot(B, C)
print(hasil_BxC)

[[ 0  2  3]
 [-3  1  3]]


## 2 a.

In [27]:
import math

# Menghitung 6!
hasil = math.factorial(6)

# Menampilkan hasil
print("Hasil dari 6! adalah:", hasil)

Hasil dari 6! adalah: 720


## 2 b.

In [26]:
import math

# Menghitung 8! dan 5!
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)

# Operasi pembagian
hasil = faktorial_8 / faktorial_5

# Menampilkan hasil
print("Hasil dari 8! / 5! adalah:", hasil)

Hasil dari 8! / 5! adalah: 336.0


## 3

In [28]:
import numpy as np

# Mendefinisikan vektor A dan B
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Menghitung panjang masing-masing vektor (norma)
panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

# Menghitung hasil perkalian titik (dot product)
dot_product = np.dot(A, B)

# Menghitung hasil perkalian silang (cross product)
cross_product = np.cross(A, B)

# Menampilkan hasil
print("Panjang vektor A:", panjang_A)
print("Panjang vektor B:", panjang_B)
print("Hasil perkalian titik (A . B):", dot_product)
print("Hasil perkalian silang (A x B):", cross_product)

Panjang vektor A: 9.1104335791443
Panjang vektor B: 12.409673645990857
Hasil perkalian titik (A . B): 58
Hasil perkalian silang (A x B): [ 24  79 -51]
